### ISSUE TITLE
Error in when looking up words

### ISSUE THREAD

**Issue by KennethEnevoldsen** [Guscode/Sentida#1]
Running on MacOS.

Traceback:
```
Error in get(word, envir = env, inherits = FALSE) : 
  object 'nødhjælp' not found 
5.
get(word, envir = env, inherits = FALSE) 
4.
sentida(x, output = "mean") 
```

Code to reproduce:
```
sentida("hjælp", output = "mean")
Error in get(word, envir = env, inherits = FALSE) : 
  object 'hjælp' not found
```

Code which apparently work:
```
> sentida("Æ", output = "mean")
[1] 0
> sentida("æ", output = "mean")
[1] 0
```

have tried to run the `Sys.setlocale(category = "LC_ALL", locale = "UTF-8")`

**Comment by jacdals97** [comment]
@KennethEnevoldsen 
Thanks for bringing it to our attention
Back in december we made a performance update which changed the way words are looked up in R. It seems that the new data structure (built in Windows) can't handle words in the Sentida dictionary containing æøå on MacOS
Now, MacOS uses the old lookup method (about half speed)
